services:
    resource.discuss.order_filter:
        parent:    "api.doctrine.orm.order_filter"
        arguments: [ ~ ] # This line can also be omitted

    resource.discuss.collection_operation.get:
            class:     "Dunglas\ApiBundle\Api\Operation\Operation"
            public:    false
            factory:   [ "@api.operation_factory", "createItemOperation" ]
            arguments: [ "@resource.discuss", "GET" ]

    resource.discuss.item_operation.get:
            class:     "Dunglas\ApiBundle\Api\Operation\Operation"
            public:    false
            factory:   [ "@api.operation_factory", "createItemOperation" ]
            arguments: [ "@resource.discuss", "GET" ]

    resource.discuss.item_operation.put:
            class:     "Dunglas\ApiBundle\Api\Operation\Operation"
            public:    false
            factory:   [ "@api.operation_factory", "createItemOperation" ]
            arguments: [ "@resource.discuss", "PUT" ]

    resource.discuss.item_operation.delete:
                class:     "Dunglas\ApiBundle\Api\Operation\Operation"
                public:    false
                factory:   [ "@api.operation_factory", "createItemOperation" ]
                arguments: [ "@resource.discuss", "DELETE" ]

    resource.discuss:
        parent:    "api.resource"
        arguments: [ "PlotComBundle\\Entity\\Discuss" ]
        calls:
            -      [ "initItemOperations", [ [ "@resource.discuss.item_operation.get","@resource.discuss.item_operation.delete","@resource.discuss.item_operation.put"] ] ]
        tags:      [ { name: "api.resource" } ]
