services:
  api_listener_prePersist:
      class:  PlotComBundle\Listener\ApiListener
      arguments: [@service_container]
      tags:
          - { name: kernel.event_listener, event: api.pre_create, method: prePersist }
