security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy: ~
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        oauth_token:
            pattern:    ^api/v1/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^api/v1/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous : true

        api:
            pattern:    ^/api/v1
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value

        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                use_forward: false
                check_path: fos_user_security_check
                failure_path: null
                default_target_path: /
                remember_me: true
            remember_me:
                key: %secret%
                lifetime: 30000000
                path: /
                domain: -
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true

    access_control:
        #- { path: ^/api/v1, roles: [ IS_AUTHENTICATED_FULLY ] }





